---
ID: "65241cf4-eb79-41ed-81f6-ba44c1648aa5"
Parent: "3d43efda-19db-45c0-99fd-6c3e1163c61d"
Template: "3d43efda-19db-45c0-99fd-6c3e1163c61d"
Path: /sitecore/templates/Feature/Articles/Article/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
- ID: "f7b94d8c-a842-49f8-ab7a-2169d00426b0"
  Hint: __Should Not Organize In Bucket
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201001T160830Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "f20d6efb-5f06-4634-bb58-53b426531990"
      Hint: Title
      Value: $name
